# When set to false, ignores files with "GENERATED" header, similar to golint
ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0

# turning all rules off as some of them needs explicit configuration
# enableAllRules = true
#
# [rule.max-public-structs]
#   arguments =[0]
# [rule.line-length-limit]
#   arguments =[120]

[rule.blank-imports]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.dot-imports]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.exported]
    # disable only for personal projects
    Disabled = true
[rule.if-return]
[rule.increment-decrement]
[rule.var-naming]
[rule.var-declaration]
[rule.package-comments]
    # disable only for personal projects
    Disabled = true
    # severity = "warning"
[rule.range]
[rule.receiver-naming]
[rule.time-naming]
[rule.unexported-return]
[rule.indent-error-flow]
[rule.errorf]
[rule.empty-block]
[rule.superfluous-else]
[rule.unused-parameter]
[rule.unreachable-code]
[rule.redefines-builtin-id]
