swipe:
  3:
    left:
      # command: "xdotool key alt+Left"
      sendkey: "LEFTALT+RIGHT" # History back
    right:
      # command: "xdotool key alt+Right"
      sendkey: "LEFTALT+LEFT" # History forward
    up:
      # command: "xdotool key ctrl+t"
      sendkey: "LEFTCTRL+T" # Open a new tab
      # keypress:
      # LEFTSHIFT:
      #   command: "xdotool key --clearmodifiers ctrl+shift+t" # Open last closed tab
    down:
      # command: "xdotool key ctrl+w" # Close tab
      sendkey: "LEFTCTRL+W" # Close a tab

  4:
    left:
      command: exec i3 focus left
    right:
      command: exec i3 focus right
    up:
      command: exec i3 fullscreen toggle
    down:
      command: exec i3 floating toggle
pinch:
  in:
    # command: "xdotool key ctrl+plus"
    sendkey: "LEFTCTRL+plus"
  out:
    sendkey: "LEFTCTRL+minus"

threshold:
  swipe: 0.4
  pinch: 0.4

interval:
  swipe: 0.8
  pinch: 0.1
