; https://man.archlinux.org/man/fuzzel.ini.5.en#:~:text=fuzzel.ini%20-%20configuration%20file%20for%20fuzzel(1)%20DESCRIPTION.%20fuzzel%20uses%20the
dpi-aware=no
icon-theme=Papirus-Dark
width=80
font=JetBrainsMono:weight=bold:size=13
line-height=16
fields=name,generic,comment,categories,filename,keywords,exec
terminal=ghostty -e
prompt="❯   "
show-actions=yes
exit-on-keyboard-focus-loss=no
layer=overlay
lines=15

[dmenu]
exit-immediately-if-empty=yes

[colors]
; background=1e1e2eaa
; text=cdd6f4ff
text=76946aff
; match=f38ba8ff
match=c34043ff
; selection=585b70ff
; selection-match=f38ba8ff
selection-match=c34043ff
; selection-text=cdd6f4ff
selection-text=c8c093ff
; border=b4befeff

; background=282a36fa
background=1f1f28ff
; background=404552ff
selection=3d4474fa
; border=fffffffa
border=6a9589ff
input=c8c093ff

[border]
radius=20
width=3

[key-bindings]
next=Control+j
prev=Control+k
delete-line-forward=Control+p

; background = '#1f1f28'
; foreground = '#dcd7ba'
;
; [colors.normal]
; black = '#090618'
; red = '#c34043'
; green = '#76946a'
; yellow = '#c0a36e'
; blue = '#7e9cd8'
; magenta = '#957fb8'
; cyan = '#6a9589'
; white = '#c8c093'
;
; [colors.bright]
; black = '#727169'
; red = '#e82424'
; green = '#98bb6c'
; yellow = '#e6c384'
; blue = '#7fb4ca'
; magenta = '#938aa9'
; cyan = '#7aa89f'
; white = '#dcd7ba'
;
; [colors.selection]
; background = '#2d4f67'
; foreground = '#c8c093'
;
; [[colors.indexed_colors]]
; index = 16
; color = '#ffa066'
;
; [[colors.indexed_colors]]
; index = 17
; color = '#ff5d62'
