#!/bin/sh
# Simple script to show the CPU temperature formatted for use with i3blocks
# temp=$(acpi -t | sed 's/.*, //;s/ degrees //;s/C//')
temp=$(sensors | grep -E "^CPU:" | awk '{print $2}' | sed 's/+//;s/C//')
# echo $temp°C
echo "$temp"C
#
# if [ 1 -eq "$(echo "$temp > 70" | bc)" ]; then
#     echo "#FF2E00"
# elif [ 1 -eq "$(echo "$temp > 60" | bc)" ]; then
#     echo "#FF8400"
# elif [ 1 -eq "$(echo "$temp > 50" | bc)" ]; then
#     echo "#FFF600"
# fi
